#Include "./configs/config.ahk"
#Include "./configs/menu.ahk"

#Include "./modules/mode-3.ahk"
#Include "./modules/mode-9.ahk"
#Include "./modules/mode-caps.ahk"
#Include "./modules/mode-mac.ahk"
#Include "./modules/mode-quote.ahk"
#Include "./modules/mode-semi.ahk"
#Include "./modules/mode-tab.ahk"
